In [1]:
from pandas import DataFrame, Series
import pandas as pd
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

# Creation

In [9]:
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

In [10]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

# with placeholder

In [12]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [14]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Sequence of numbers

return array instead of list

In [15]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [16]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [20]:
from numpy import pi
np.linspace( 0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
x = np.linspace( 0, 2*pi, 100 )
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

## From reshaping

In [24]:
b = np.arange(12).reshape(4,3)           # 2d array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
c = np.arange(24).reshape(2,3,4)         # 3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [67]:
## From Functions

def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

## Operations

In [30]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

c = a - b
c

array([20, 29, 38, 47])

In [31]:
b**2

array([0, 1, 4, 9])

In [32]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [34]:
a < 35

array([ True,  True, False, False])

In [35]:
A = np.array( [[1,1],
[0,1]] )
B = np.array( [[2,0],
[3,4]] )

## Elementwise Operation

In [40]:
A * B

array([[2, 0],
       [0, 4]])

## Matrix Multiplication

In [38]:
A@B

array([[5, 4],
       [3, 4]])

In [39]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [45]:
### inplace modification
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))

a *= 3
b += a

In [46]:
b

array([[3.00877917, 3.84842468, 3.7273562 ],
       [3.64088173, 3.02062057, 3.65773894]])

In [48]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

### Upcasting

In [51]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

## Calculation

In [52]:
b = np.arange(12).reshape(3,4)
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
b.sum()

66

In [54]:
b.sum(axis=1)

array([ 6, 22, 38])

In [55]:
b.sum(axis=0)

array([12, 15, 18, 21])

## Universal Functions

In [56]:
B = np.arange(3)
B


array([0, 1, 2])

In [57]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

## Indexing, slicing and iterating

In [60]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [59]:
a[2]

8

In [61]:
a[2:5]

array([ 8, 27, 64])

In [62]:
a[:6:2] = -1000

In [64]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [65]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [66]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [68]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [69]:
b[2,3]

23

In [70]:
b[0:5, 1] 

array([ 1, 11, 21, 31, 41])

In [71]:
b[0:5, (1,)] 

array([[ 1],
       [11],
       [21],
       [31],
       [41]])

In [74]:
b[1, :] 

array([10, 11, 12, 13])

In [75]:
b[(1, ), :] 

array([[10, 11, 12, 13]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [76]:
b[-1]

array([40, 41, 42, 43])

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

```x[1,2,...]``` is equivalent to ```x[1,2,:,:,:]```

Iterating over multidimensional arrays is done with respect to the first axis:

In [77]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


### flat

In [80]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape manipulation

In [81]:
a = np.floor(10*np.random.random((3,4)))
a


array([[2., 8., 9., 5.],
       [0., 2., 7., 1.],
       [9., 7., 8., 1.]])

The order of the elements in the array resulting from ravel() is normally “C-style”, that is, the rightmost index “changes the fastest”, so the element after a[0,0] is a[0,1].

In [85]:
a.ravel()

array([2., 8., 9., 5., 0., 2., 7., 1., 9., 7., 8., 1.])

In [86]:
a.reshape(6,2)

array([[2., 8.],
       [9., 5.],
       [0., 2.],
       [7., 1.],
       [9., 7.],
       [8., 1.]])

In [87]:
a.T

array([[2., 0., 9.],
       [8., 2., 7.],
       [9., 7., 8.],
       [5., 1., 1.]])

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [88]:
a = np.floor(10*np.random.random((3,4)))
a.resize(2, 6)
a

array([[3., 7., 7., 0., 1., 3.],
       [2., 2., 5., 0., 6., 4.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [90]:
a.reshape(3,-1)

array([[3., 7., 7., 0.],
       [1., 3., 2., 2.],
       [5., 0., 6., 4.]])

In [91]:
a.reshape(-1, -1)

ValueError: can only specify one unknown dimension

## stacking

In [92]:
a = np.floor(10*np.random.random((2,2)))
a


array([[1., 3.],
       [1., 4.]])

In [93]:
b = np.floor(10*np.random.random((2,2)))
b

array([[4., 5.],
       [5., 8.]])

In [94]:
np.vstack([a, b])

array([[1., 3.],
       [1., 4.],
       [4., 5.],
       [5., 8.]])

In [95]:
np.hstack([a, b])

array([[1., 3., 4., 5.],
       [1., 4., 5., 8.]])

In [96]:
np.column_stack((a,b))

array([[1., 3., 4., 5.],
       [1., 4., 5., 8.]])

In [97]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [98]:
from numpy import newaxis

In [99]:
a[:,newaxis]

array([[4.],
       [2.]])

In [100]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [101]:
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [102]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [125]:
a = np.floor(10*np.random.random((2,12)))
a

array([[0., 2., 8., 0., 8., 8., 3., 8., 3., 4., 2., 3.],
       [4., 1., 6., 5., 9., 5., 7., 4., 3., 4., 0., 5.]])

In [126]:
np.hsplit(a,3)   # Split a into 3

[array([[0., 2., 8., 0.],
        [4., 1., 6., 5.]]), array([[8., 8., 3., 8.],
        [9., 5., 7., 4.]]), array([[3., 4., 2., 3.],
        [3., 4., 0., 5.]])]

In [127]:
splits = np.hsplit(a, (3, 4)) # Split a after the third and the fourth column

In [128]:
splits

[array([[0., 2., 8.],
        [4., 1., 6.]]), array([[0.],
        [5.]]), array([[8., 8., 3., 8., 3., 4., 2., 3.],
        [9., 5., 7., 4., 3., 4., 0., 5.]])]

In [129]:
splits[1]

array([[0.],
       [5.]])

In [130]:
splits[2]

array([[8., 8., 3., 8., 3., 4., 2., 3.],
       [9., 5., 7., 4., 3., 4., 0., 5.]])

In [131]:
# Copies and Views

In [132]:
a = np.arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object


True

In [134]:
b.shape = 3,4    # changes the shape of a
a.shape

(3, 4)

## Python passes mutable objects as references, so function calls make no copy.

In [136]:
def f(x):
    print(id(x))

id(a)                           # id is a unique identifier of an object


4544692512

In [138]:
f(a)

4544692512
